export const APIS = {
  LOAD: 'LOAD_APIS'
};

export const UI = {
  OPEN_CREATE_API_MODAL: 'OPEN_CREATE_API_MODAL',
  CLOSE_CREATE_API_MODAL: 'CLOSE_CREATE_API_MODAL',
  OPEN_UPDATE_API_MODAL: 'OPEN_UPDATE_API_MODAL',
  CLOSE_UPDATE_API_MODAL: 'CLOSE_UPDATE_API_MODAL',
  OPEN_REMOVE_API_MODAL: 'OPEN_REMOVE_API_MODAL',
  CLOSE_REMOVE_API_MODAL: 'CLOSE_REMOVE_API_MODAL'
};