export const APIS = {
    LOAD: 'LOAD_APIS',
    LOAD_API: 'LOAD_API',
    SELECT_API: 'SELECT_API',
    DESELECT_API: 'DESELECT_API'
};

export const UI = {
    IS_OPEN_TRUE: 'IS_OPEN_TRUE',
    IS_SECOND_OPEN_TRUE: 'IS_SECOND_OPEN_TRUE',
    IS_OPEN_FALSE: 'IS_OPEN_FALSE',
    IS_SECOND_OPEN_FALSE: 'IS_SECOND_OPEN_FALSE',
    OPEN_CREATE_API_MODAL: 'OPEN_CREATE_API_MODAL',
    CLOSE_CREATE_API_MODAL: 'CLOSE_CREATE_API_MODAL',
    OPEN_UPDATE_API_MODAL: 'OPEN_UPDATE_API_MODAL',
    CLOSE_UPDATE_API_MODAL: 'CLOSE_UPDATE_API_MODAL',
    OPEN_REMOVE_API_MODAL: 'OPEN_REMOVE_API_MODAL',
    CLOSE_REMOVE_API_MODAL: 'CLOSE_REMOVE_API_MODAL',
    OPEN_API_ROUTES_MODAL: 'OPEN_API_ROUTES_MODAL',
    CLOSE_API_ROUTES_MODAL: 'CLOSE_API_ROUTES_MODAL'
};