export const APIS = {
  LOAD: 'LOAD_APIS',
  SELECT_API: 'SELECT_API',
  DESELECT_API: 'DESELECT_API'
};

export const UI = {
  OPEN_CREATE_API_MODAL: 'OPEN_CREATE_API_MODAL',
  CLOSE_CREATE_API_MODAL: 'CLOSE_CREATE_API_MODAL',
  OPEN_UPDATE_API_MODAL: 'OPEN_UPDATE_API_MODAL',
  CLOSE_UPDATE_API_MODAL: 'CLOSE_UPDATE_API_MODAL',
  OPEN_REMOVE_API_MODAL: 'OPEN_REMOVE_API_MODAL',
  CLOSE_REMOVE_API_MODAL: 'CLOSE_REMOVE_API_MODAL'
};